id: P006879
initial_creation_type: ocr
created_at: 27/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG2807
  title: མཁས་འཇུག་གི་ས་བཅད་དང་སྡོམ་བྱང་དང་མཁས་པའི་ཚུལ་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་བསྟན་བཅོས་སོགས
  author: ''
  volumes:
    4df191d1a1f14673a657375db716fd0d:
      image_group_id: I1KG3149
      title: ''
      volume_number: 1
      total_pages: 428
      base_file: v001.txt
