id: opecha:P006879
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG2807
  title: མཁས་འཇུག་གི་ས་བཅད་དང་སྡོམ་བྱང་དང་མཁས་པའི་ཚུལ་ལ་འཇུག་པའི་སྒོ་ཞེས་བྱ་བའི་བསྟན་བཅོས་སོགས
  volume: ''
  author: ''
